#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         PBS
version:      0.02
version_from: lib/PBS.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
